yocto 3.1 dunfell build fixes (#5)
* cobalt_source.cc - fix for G_ADD_PRIVATE [-Werror]

| .../third_party/starboard/raspi/wayland/starboard_platform.cobalt_source.o
| ../../third_party/starboard/raspi/wayland/cobalt_source.cc:97:13: error: G_ADD_PRIVATE [-Werror]
|    97 |   GstCobaltSrcPrivate* priv = GST_COBALT_SRC_GET_PRIVATE(src);
|       |             ^~~~~~~~~~~~~~~
| cc1plus: all warnings being treated as errors

* compiler-flags: fix for -Werror=invalid-offsetof

offsetof() usage causing error due to this flag on gcc 9.3 or higher